SELECT * FROM OE_ORDER_HEADERS_ALL WHERE ORDER_NUMBER=69413;
DESC OE_ORDER_LINES_ALL;
SELECT FLOW_STATUS_CODE,BOOKED_FLAG,OPEN_FLAG FROM OE_ORDER_LINES_ALL WHERE HEADER_ID=366804;
DESC MTL_RESERVATIONS;
SELECT * FROM MTL_RESERVATIONS;
SELECT * FROM MTL_RESERVATIONS WHERE organization_id=204 AND demand_source_line_id=678235;

SELECT * FROM MTL_DEMAND WHERE ORGANIZATION_ID = 204 AND demand_source_line=679220;

DESC WSH_DELIVERY_DETAILS;
SELECT * FROM WSH_DELIVERY_DETAILS WHERE source_line_ID=679220;

---No Delivery ID

SELECT * FROM WSH_DELIVERY_ASSIGNMENTS WHERE delivery_detail_id =6223052;



SELECT * FROM MTL_DEMAND WHERE demand_source_line=678239;


SELECT *  FROM WSH_NEW_DELIVERIES WHERE source_header_id = 366780;

SELECT * FROM MTL_TXN_REQUEST_HEADERS;

DESC MTL_MATERIAL_TRANSACTIONS;

SELECT * FROM MTL_MATERIAL_TRANSACTIONS WHERE TRX_SOURCE_LINE_ID =679223;
SELECT * FROM MTL_TXN_REQUEST_HEADERS WHERE HEADER_ID=6393360; 
SELECT * FROM MTL_TXN_REQUEST_LINES WHERE TXN_SOURCE_LINE_ID =679220;
