--IMplicit conversion of VARCHAR2 to NUMBER
SELECT * FROM EMPLOYEES WHERE SALARY >'5000';

--VARCHAR TO DATE implicit conversion
SELECT * FROM EMPLOYEES WHERE HIRE_DATE='17-JUN-03';

--NUMBER TO VARCHAR2

SELECT DEPARTMENT_ID || DEPARTMENT_NAME FROM departments;

--DATE TO VARCHAR2
SELECT FIRST_NAME || HIRE_DATE FROM employees;