SELECT FLOW_STATUS_CODE,BOOKED_FLAG,OPEN_FLAG FROM OE_ORDER_HEADERS_ALL WHERE ORDER_NUMBER=69413;

SELECT FLOW_STATUS_CODE,BOOKED_FLAG,OPEN_FLAG FROM OE_ORDER_LINES_ALL WHERE HEADER_ID=366804;

DESC MTL_RESERVATIONS;



SELECT * FROM MTL_RESERVATIONS WHERE organization_id = 204 and demand_source_line_id=679230;

SELECT * FROM MTL_DEMAND WHERE ORGANIZATION_ID = 204 AND demand_source_line=679230;


DESC WSH_DELIVERY
SELECT * FROM WSH_DELIVERY_DETAILS WHERE source_line_ID=679223;


SELECT * FROM WSH_NEW_DELIVERIES;

DESC WSH_DELIVERY_ASSIGNMENTS ;
SELECT * FROM WSH_DELIVERY_ASSIGNMENTS WHERE delivery_detail_id=6223055;


DESC MTL_DEMAND;
SELECT * FROM MTL_DEMAND WHERE DEMAND_SOURCE_HEADER_ID=366814;