CREATE TABLE EMPLOYEES_COPY_PETER AS

SELECT FIRST_NAME,LAST_NAME ,SALARY FROM EMPLOYEES WHERE JOB_ID='IT_PROG';

SELECT * FROM employees_copy_peter;


CREATE TABLE TEST_8
(columm1 VARCHAR2(6) NOT NULL,
Column2 varchar2 (10));

INSERT INTO TEST_8 (column2)
VALUES ( 'Male');

desc test_8;


ALTER TABLE TEST_8 MODIFY COLUMN2 NOT NULL;