SET SERVEROUTPUT ON
BEGIN
DBMS_OUTPUT.PUT_LINE(SYSDATE);
END;

SET SERVEROUTPUT ON
DECLARE 
V_DATE VARCHAR2(5);
BEGIN
V_DATE:='Hello guys';
DBMS_OUTPUT.PUT_LINE(V_DATE);

EXCEPTION 
WHEN 
VALUE_ERROR
THEN
DBMS_OUTPUT.PUT_LINE('This is how to handle exception');
END;
