SELECT APS.VENDOR_ID,
       APS.VENDOR_NAME,
       API.INVOICE_ID,
       API.INVOICE_AMOUNT,
       API.TOTAL_TAX_AMOUNT,
       API.LAST_UPDATE_DATE,
      AILA.TAX_RATE_CODE,
       --ZRB.TAX_RATE_CODE,
       API.INVOICE_NUM,
       AILA.DESCRIPTION,
       AILA.ACCOUNTING_DATE
FROM AP_SUPPLIERS APS
JOIN AP_INVOICES_ALL      API ON APS.VENDOR_ID = API.VENDOR_ID
JOIN AP_INVOICE_LINES_ALL AILA ON AILA.INVOICE_ID = API.INVOICE_ID
-- JOIN ZX_RATES_B           ZRB ON AILA.TAX_RATE_CODE = ZRB.TAX_RATE_CODE
WHERE APS.SEGMENT1 = '&VENDOR_ID'  ORDER BY ACCOUNTING_DATE DESC;
--AND AILA.ACCOUNTING_DATE BETWEEN '01-AUG-22' AND '30-SEP-22';
--WHERE APS.VENDOR_ID = '&SUPPLIER_ID';
---Supplierid 1015


select * from ap_suppliers order by creation_date desc;