SELECT APIA.INVOICE_NUM,
APIA.INVOICE_AMOUNT,
       APIA.DISCOUNT_AMOUNT_TAKEN DISCOUNT_AMOUNT,
       AILA.ACCOUNTING_DATE       DATE_PAID,
       APIA.TAX_AMOUNT,
       AILA.TAX_RATE_CODE,
       APS.TAX_REPORTING_NAME
FROM AP_INVOICES_ALL APIA
JOIN AP_INVOICE_LINES_ALL AILA ON AILA.INVOICE_ID = APIA.INVOICE_ID
JOIN AP_SUPPLIERS      APS ON APS.VENDOR_ID = APIA.VENDOR_ID WHERE APS.SEGMENT1 = '&PO_NUMBER';